const naverSearch = (query) => `https://map.naver.com/p/search/${encodeURIComponent(query)}`;
const googleSearch = (query) => `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query)}`;

export const tripMeta = {
  title: "韓國五日遊",
  subtitle: "比賽、首爾散策與水原小旅行",
  dates: "2026.09.11 — 09.15",
  hotel: "HOMES Stay Suwon",
  hotelAddress: "경기도 수원시 팔달구 인계로 116",
  flightOut: "BR170 · TPE 07:30 → ICN 11:00",
  flightBack: "BR159 · ICN 19:45 → TPE 21:25",
};

export const seoulAreas = [
  {
    name: "弘大＋延南洞", korean: "홍대 · 연남동", tag: "前兩晚住宿候選", stay: "半天＋晚上",
    lat: 37.5587, lng: 126.9245, query: "홍대입구역 연남동",
    character: "年輕、熱鬧、餐廳密集；兩區相鄰，適合串成同一天。",
    friendNote: "弘大主街適合吃飯和看街頭表演；延南洞可沿主要幹道逛品牌店，但步行距離偏長。",
    planning: "晚上覓食方便，也有 AREX；穿好走的鞋，逛街區不要排得太細。",
  },
  {
    name: "汝矣島", korean: "여의도", tag: "下雨首選", stay: "半天～一日",
    lat: 37.5258, lng: 126.9284, query: "더현대 서울",
    character: "The Hyundai Seoul 一站式購物，旁邊可接汝矣島漢江公園。",
    friendNote: "百貨品牌完整；下雨可待一整天，天氣好則到漢江公園煮泡麵、看夕陽。",
    planning: "購物與夕陽一次完成，適合當雨天備案；週末百貨人潮多。",
  },
  {
    name: "漢南洞", korean: "한남동", tag: "氛圍與街拍", stay: "2–4 小時",
    lat: 37.5367, lng: 127.0006, query: "한남동 카페거리",
    character: "設計品牌、藝廊與咖啡店散落在坡道街區，像城市裡的選品散策。",
    friendNote: "氛圍感很好、潮牌單價高，購買 CP 值因人而異；可順路看看 Helinox。",
    planning: "坡多且店家不集中，適合有目標地逛，不建議把它當大量採買區。",
  },
  {
    name: "狎鷗亭", korean: "압구정", tag: "集中逛潮牌", stay: "3–5 小時",
    lat: 37.5274, lng: 127.0389, query: "압구정 로데오거리",
    character: "潮牌、美式風格與旗艦店較集中，適合鎖定品牌快速逛。",
    friendNote: "雖然只逛了一下，但體感是店家集中、最好逛的區域之一。",
    planning: "可與漢南洞擇一或串聯；先列品牌清單，避免在高價店區漫無目的移動。",
  },
  {
    name: "聖水洞", korean: "성수동", tag: "建築＋品牌首選", stay: "半天～一日",
    lat: 37.5446, lng: 127.0558, query: "성수동 카페거리",
    character: "紅磚工廠改建、快閃店、咖啡與品牌旗艦聚集，街區辨識度高。",
    friendNote: "多數店集中在核心幹道，省時好逛；Blue Elephant 地球視覺很有代表性。",
    planning: "朋友最推薦。可接首爾林與聖水行人天橋，把逛街、建築、夕陽排在同一天。",
  },
  {
    name: "明洞", korean: "명동", tag: "品項最齊", stay: "3–5 小時",
    lat: 37.5636, lng: 126.9850, query: "명동 쇼핑거리",
    character: "美妝、服飾、旗艦店與觀光服務集中，熱鬧且容易比價。",
    friendNote: "有西門町的既視感，店舖多、種類完整。",
    planning: "適合最後補貨與藥妝比價；熱門時段擁擠，別把街頭換匯當唯一現金來源。",
  },
  {
    name: "新沙洞", korean: "신사동", tag: "有目標才去", stay: "1–3 小時",
    lat: 37.5200, lng: 127.0230, query: "신사동 가로수길",
    character: "林蔭道與周邊支巷曾是代表性逛街區，現況與店家更替速度快。",
    friendNote: "當次體驗店少、人少；若沒有指定店家，優先度可以降低。",
    planning: "出發前先用 Naver Map 確認目的店仍營業，再決定是否專程前往。",
  },
  {
    name: "蠶室＋石村湖", korean: "잠실 · 석촌호수", tag: "百貨＋湖景", stay: "半天～一日",
    lat: 37.5112, lng: 127.0980, query: "석촌호수 롯데월드몰",
    character: "石村湖、樂天世界塔與大型購物中心集中，室內外都能安排。",
    friendNote: "樂天世界商城品牌很多，但位於首爾東側，移動距離較長。",
    planning: "除非想去樂天或拍湖景，否則短天數可讓位給聖水、弘大或汝矣島。",
  },
];

export const travelPrep = [
  {
    id: "esim", step: "01", timing: "出發前 3–7 天", title: "eSIM 與台灣門號", priority: "必做",
    summary: "先確認手機支援 eSIM 且沒有電信鎖；在有 Wi-Fi 時安裝，抵達韓國才啟用數據。",
    checklist: [
      "將韓國 eSIM 命名為「Korea」，先不要刪除 QR code／安裝信。",
      "抵達後：行動數據切到 Korea，開啟該門號的數據漫遊。",
      "台灣 SIM 保留收簡訊，但關閉數據漫遊，避免漫遊費；關閉「允許行動數據切換」。",
      "同行者不要全買同一家電信商；至少一人保留不同網路作備援。",
    ],
  },
  {
    id: "arrival", step: "02", timing: "抵達日前 3 天內", title: "韓國電子入境申報", priority: "視資格",
    summary: "只使用官方 e-Arrival Card 網站，免費填寫；持有效 K-ETA 等豁免者可能不用填，先用官方 Navigator 判定。",
    checklist: [
      "準備護照、抵離境航班、韓國住宿名稱／地址及可收驗證碼的 Email。",
      "以韓國標準時間計算，抵達日前 3 天起才可提交；2026/5/6 起提交加入驗證碼步驟。",
      "若已提交電子版本，不需再填紙本；任何要求付款的網站都不是官方服務。",
    ],
    source: "https://www.e-arrivalcard.go.kr/portal/main/index.do?locale=E", sourceLabel: "官方 e-Arrival Card",
  },
  {
    id: "smartpass", step: "03", timing: "出發前先裝、回程再登錄", title: "ICN SmartPass", priority: "建議",
    summary: "SmartPass 是仁川機場的出境人臉通行服務，不是入境韓國的申報或移民查驗。",
    checklist: [
      "先在官方 App 掃描電子護照並註冊臉部資料；護照換發後需重登。",
      "每次出境仍要登錄登機證；BR159 完成報到後確認 App 內是否成功加入。",
      "可使用指定出境通道；仍須隨身攜帶護照與登機證，並照常接受安檢／移民查驗。",
    ],
    source: "https://airinfo.airport.kr/ap_en/1415/subview.do", sourceLabel: "仁川機場 SmartPass",
  },
  {
    id: "payment", step: "04", timing: "出發前", title: "付款與韓元配置", priority: "必做",
    summary: "採「海外回饋信用卡＋實體 T-money＋少量韓元」三層備援，不把單一 App 當唯一支付方式。",
    checklist: [
      "信用卡開啟海外交易通知，準備另一張不同卡組織的備用卡並分開存放。",
      "韓元用於交通卡加值、市場、小店與緊急狀況；先換少量，市區再視需求補充。",
      "結帳若可選幣別，通常選 KRW，避免商家動態匯率轉換（DCC）。",
      "重要卡片與現金分開放；記下銀行海外掛失電話。",
    ],
  },
  {
    id: "tmoney", step: "05", timing: "抵達機場後", title: "T-money：實體卡最穩", priority: "必做",
    summary: "台灣旅客以便利商店或機場購買的實體 T-money 最簡單；搭車上下車都要感應。",
    checklist: [
      "先儲值約 ₩20,000–30,000，再依餘額補充；保留一些小額現金加值。",
      "iPhone 雖可把 T-money 加入 Apple Wallet，但 Apple 官方註明購買／加值需要韓國發行的信用卡或金融卡。",
      "因此不要把 Mobile Tmoney／Apple Wallet 當台灣旅客唯一方案；實體卡可直接備援。",
    ],
    source: "https://support.apple.com/en-us/105079", sourceLabel: "Apple Wallet 交通卡說明",
  },
  {
    id: "apps", step: "06", timing: "出發前下載", title: "地圖、交通與翻譯 App", priority: "建議",
    summary: "Naver Map 查店家與大眾運輸，Google Maps 輔助看街廓與月台方向，Papago 處理韓文翻譯。",
    checklist: [
      "在 Naver Map 先收藏飯店、機場、每日第一站與備用餐廳，名稱優先使用韓文。",
      "截圖飯店韓文地址與電話，網路失效時可直接給司機或工作人員看。",
      "Papago 下載需要的離線語言資源；相機翻譯適合菜單，但過敏資訊仍要人工再次確認。",
    ],
  },
  {
    id: "airport", step: "07", timing: "入境與離境", title: "機場交通、SES 與退稅", priority: "提醒",
    summary: "大行李可優先選機場巴士；SES 自動通關屬選配，不要為辦理它壓縮團體集合時間。",
    checklist: [
      "機場巴士座位舒適、免搬行李轉乘，但遇塞車會較慢；趕時間改搭 AREX。",
      "台灣旅客的自動通關適用資格與現場服務時間可能變動，抵達後以移民署服務台公告為準。",
      "購物時先問是否能即時退稅；否則收好 Tax Refund 憑證、護照與商品，依憑證指示到機場辦理。",
      "BR159 由 ICN T1 出發；若需一般退稅，預留比只辦登機更多的機場時間。",
    ],
    source: "https://english.visitkorea.or.kr/svc/contents/contentsView.do?menuSn=929&vcontsId=248765", sourceLabel: "VISITKOREA 退稅指南",
  },
  {
    id: "restroom", step: "08", timing: "旅途中隨時", title: "臨時找廁所", priority: "實用",
    summary: "在 Naver Map 或 Kakao Map 搜尋韓文關鍵字，比輸入中文或英文 restroom 更容易找到附近設施。",
    checklist: [
      "搜尋「화장실」＝廁所。",
      "搜尋「공용화장실」＝公用／公共廁所。",
      "可直接複製韓文關鍵字到地圖 App；抵達後再看營業時間、所在樓層與是否位於地鐵站內。",
    ],
  },
];

export const culinaryRestaurants = [
  {
    name: "VIA TOLEDO Pasta Bar", korean: "비아톨레도 파스타바", season: "第一季",
    chef: "權聖晙｜拿坡里黑手黨", role: "第一季冠軍", price: "課程制・高價",
    area: "南營／龍山", query: "비아톨레도 파스타바", lat: 37.5402, lng: 126.9686,
    signature: "季節義大利麵與多道式套餐",
    why: "想體驗節目冠軍的完整料理世界，這間辨識度最高；餐單與擺盤有濃厚義大利旅行感。",
    route: "可接首爾站、南大門或龍山；需預留完整晚餐時間。",
    solo: "先確認是否開放 1 人座位；熱門日期通常要提早搶位。",
    booking: "https://www.catchtable.net/shop/viatoledo",
    source: "https://english.visitkorea.or.kr/svc/contents/infoHtmlView.do?vcontsId=214935",
  },
  {
    name: "trid", korean: "트리드", season: "第一季",
    chef: "姜承元｜三星", role: "黑湯匙人氣主廚", price: "課程制・高價",
    area: "狎鷗亭羅德奧", query: "트리드 청담", lat: 37.5260, lng: 127.0407,
    signature: "現代西式套餐、細緻醬汁與精準擺盤",
    why: "重視技術感、視覺與服務完整度時的慶祝餐選擇。",
    route: "和狎鷗亭購物安排同一天，午餐比晚餐更好控制行程。",
    solo: "課程約需 2–3 小時；訂位時先確認單人與訂金規則。",
    booking: "https://www.catchtable.net/shop/trid",
    source: "https://english.visitkorea.or.kr/svc/contents/infoHtmlView.do?vcontsId=214935",
  },
  {
    name: "Deepin", korean: "디핀 신당", season: "第一季",
    chef: "尹男老｜料理狂人", role: "黑湯匙人氣主廚", price: "單點・中高價",
    area: "新堂", query: "디핀 신당", lat: 37.5652, lng: 127.0194,
    signature: "自然酒、海鮮、肉料理與季節單點",
    why: "比全套 fine dining 更有彈性，適合想感受主廚風格、又不想吃完整套餐的人。",
    route: "可接 DDP、乙支路或東大門夜間行程。",
    solo: "酒吧型態較適合單人，但部分菜適合分享；先看當日菜單。",
    booking: "https://www.catchtable.net/shop/deepin",
    source: "https://english.visitkorea.or.kr/svc/contents/infoHtmlView.do?vcontsId=214935",
  },
  {
    name: "Yun Seoul", korean: "윤서울", season: "第一、二季",
    chef: "金度潤｜戴耳機的主廚", role: "白湯匙", price: "課程制・高價",
    area: "狎鷗亭羅德奧", query: "윤서울", lat: 37.5248, lng: 127.0394,
    signature: "發酵、熟成、乾燥技法的當代韓食",
    why: "不是單純複製傳統韓食，而是用食材處理技法建立完整敘事，適合把一餐當旅行主題。",
    route: "可與 trid 二選一，不建議同一趟排兩間高價套餐。",
    solo: "確認單人訂位；傳統酒 pairing 另計，預算要一起評估。",
    booking: "https://www.catchtable.net/shop/yunseoul",
    source: "https://english.visitkorea.or.kr/svc/contents/infoHtmlView.do?vcontsId=214935",
  },
  {
    name: "麵首爾", korean: "면서울", season: "第一、二季",
    chef: "金度潤｜戴耳機的主廚", role: "白湯匙・米其林必比登", price: "單點麵食・中價",
    area: "狎鷗亭羅德奧", query: "면서울 선릉로 805", lat: 37.5249, lng: 127.0395,
    signature: "生紫蘇油麵、辣拌麵、蕨菜芝麻麵",
    why: "把 Yun Seoul 的自製麵研究做成較容易入門的單點餐廳；能專心體驗麵體、發酵與韓國食材，不必吃完整高價套餐。",
    route: "位於江南區宣陵路 805；可為餐廳單獨前往，不需要搭配精品購物。和 Yun Seoul 二選一即可。",
    solo: "一人一碗、適合獨食；近期資料顯示以現場候位為主，出發前重新確認候位與休息時間。",
    booking: "",
    source: "https://guide.michelin.com/kr/ko/seoul-capital-area/kr-seoul/restaurant/myeon-seoul",
    officialSource: "https://guide.michelin.com/ca/en/article/people/chef-kim-doyoon-shines-in-culinary-class-war-the-art-of-food-and-human-connection",
  },
  {
    name: "Osteria Sam Kim", korean: "오스테리아 샘킴", season: "第二季",
    chef: "Sam Kim", role: "白湯匙", price: "單點・中高價",
    area: "合井／弘大", query: "오스테리아 샘킴", lat: 37.5488, lng: 126.9169,
    signature: "章魚肉醬義大利麵、季節義式單點",
    why: "相較課程餐更容易排進旅程，適合弘大、延南洞逛街後吃一頓有節目連結的晚餐。",
    route: "直接併入弘大＋延南洞日；不用為了餐廳跨城。",
    solo: "單點較友善，但熱門時段仍應預約；部分主菜適合分享。",
    booking: "https://www.catchtable.net/shop/samkim",
    source: "https://www.catchtable.net/discovery/culinary-class-wars-2-restaurants-of-the-hottest-chefs-black-white-alliance-match-teams-of-two-2.html",
  },
  {
    name: "Congdu Myeongdong", korean: "콩두 명동", season: "第二季",
    chef: "朴孝男", role: "白湯匙・法餐名匠", price: "早餐／午餐較易入門",
    area: "明洞", query: "콩두 명동", lat: 37.5641, lng: 126.9846,
    signature: "以法式技法重構的現代韓食",
    why: "位置最容易和一般觀光路線結合；午餐價位與時間通常比晚間 tasting 親切。",
    route: "可接明洞補貨、德壽宮、南大門，適合 9/19 以前的市中心日。",
    solo: "優先查平日午餐早場；不要排在搭機當天的長套餐。",
    booking: "https://www.catchtable.net/shop/congdu_myeongdong",
    source: "https://english.seoul.go.kr/the-culinary-city-of-seoul-2026-edition/",
  },
  {
    name: "SUPERPAN", korean: "수퍼판", season: "第二季",
    chef: "禹貞旭｜首爾媽媽", role: "黑湯匙", price: "Casual fine dining",
    area: "狎鷗亭／新沙", query: "수퍼판", lat: 37.5243, lng: 127.0262,
    signature: "首爾家常味、季節海鮮與精緻單點",
    why: "把熟悉的首爾家常菜做得更細緻，想吃韓國味又不想走制式宮廷料理時很合適。",
    route: "和新沙、狎鷗亭或漢南洞擇區串聯，注意坡道與跨河車程。",
    solo: "先看最低訂位人數與當日菜色；午餐通常比週末晚餐好安排。",
    booking: "https://www.catchtable.net/shop/superpan",
    source: "https://www.catchtable.net/discovery/culinary-class-wars-2-restaurants-of-the-hottest-chefs-round-2-blackwhite-one-on-one-matches-2.html",
  },
  {
    name: "Soul", korean: "소울", season: "第二季",
    chef: "金熙恩", role: "白湯匙・米其林一星", price: "課程制・高價",
    area: "解放村", query: "소울 다이닝 해방촌", lat: 37.5429, lng: 126.9879,
    signature: "以現代韓國生活文化為題的當代套餐",
    why: "比追名菜更重視完整敘事與細節，適合安排一晚正式的獨旅紀念餐。",
    route: "可接南山、梨泰院或漢南洞；解放村有坡，穿好走的鞋。",
    solo: "提早在 Catchtable 查單人位與訂金；預留 2–3 小時。",
    booking: "https://www.catchtable.net/shop/souldining",
    source: "https://english.seoul.go.kr/the-culinary-city-of-seoul-2026-edition/",
  },
  {
    name: "卡梅谷手工包子", korean: "가메골손왕만두", season: "朋友加碼",
    chef: "南大門市場經典小吃", role: "非節目餐廳", price: "平價單點・外帶",
    area: "南大門／會賢", query: "가메골손왕만두 남대문", lat: 37.5593, lng: 126.9775,
    signature: "辣味泡菜包子；原味與辣味可混裝",
    why: "現蒸包子適合當南大門散步小吃。參考文章較推薦帶泡菜、黑胡椒辛香的辣味，外帶能把胃口留給市場其他食物。",
    route: "會賢站 5 號出口附近；可接南大門市場、明洞、德壽宮，尤其適合市中心短行程。",
    solo: "外帶通常有最低個數，價格與數量以現場為準；熱門時段可能排隊，週日公休資訊出發前再確認。",
    booking: "",
    source: "https://bobbytravel.tw/gamagol/",
  },
  {
    name: "明洞餃子本店", korean: "명동교자 본점", season: "朋友加碼",
    chef: "1966 年創業的明洞老店", role: "非節目餐廳・必比登", price: "平價單點・米其林必比登",
    area: "明洞", query: "명동교자 본점 명동10길 29", lat: 37.5626, lng: 126.9857,
    signature: "刀切麵、蒸餃、辣拌麵與蒜味泡菜",
    why: "菜單精簡、出餐快，最具代表性的是濃郁雞湯刀切麵與手工餃子；重蒜泡菜風味鮮明。",
    route: "本店最新核對地址為首爾中區明洞 10 街 29，距地鐵 4 號線明洞站 8 號出口約 183 公尺；直接併入明洞購物日。",
    solo: "一人用餐可行；尖峰排隊但翻桌快。點餐與是否可共食依現場規則，營業時間出發前再查。",
    booking: "",
    source: "https://bobbytravel.tw/myeongdong-kyoja/",
    officialSource: "https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=99925",
  },
  {
    name: "母女飯卷", korean: "모녀김밥", season: "朋友加碼",
    chef: "廣藏市場元祖迷你飯卷", role: "非節目餐廳・市場小吃", price: "平價單點・外帶",
    area: "廣藏市場", query: "모녀김밥 광장시장 창경궁로 88", lat: 37.5701, lng: 126.9998,
    signature: "麻藥飯卷／迷你飯卷＋芥末醬",
    why: "迷你海苔飯卷份量小，搭配帶刺激感的芥末醬，是廣藏市場最具代表性的邊走邊吃小食之一。",
    route: "官方最新資料標示首爾鐘路區昌慶宮路 88、廣藏市場內；從鐘路五街站 8 號出口前往最直覺。",
    solo: "一人可吃，也適合外帶；先買小份，把胃口留給綠豆煎餅與市場其他食物。",
    booking: "",
    source: "https://english.visitseoul.net/PalaceArea/Mother-and-Daughters-Gimbap1/ENP014615",
  },
  {
    name: "順熙家綠豆煎餅", korean: "순희네빈대떡", season: "朋友加碼",
    chef: "廣藏市場現磨綠豆煎餅", role: "非節目餐廳・市場小吃", price: "平價單點・可外帶",
    area: "廣藏市場", query: "순희네빈대떡 종로32길 5", lat: 37.5703, lng: 126.9991,
    signature: "綠豆煎餅、肉丸與醬油沾醬",
    why: "石磨綠豆加入泡菜、蕨菜與豬肉後現場煎炸，外層酥香；搭配醬油沾醬較能平衡油脂。",
    route: "地址為首爾鐘路區鐘路 32 街 5；和母女飯卷相距很近，安排成同一輪廣藏市場小吃。",
    solo: "一份較有飽足感，獨旅建議先不要同時買太多；想多吃幾攤可詢問外帶。",
    booking: "",
    source: "https://english.visitkorea.or.kr/svc/whereToGo/locIntrdn/rgnContentsView.do?vcontsId=194106",
  },
];

export const sharedFoodFinds = [
  {
    name: "龍鬚糖小哥（街頭攤位）", korean: "명동 꿀타래", area: "明洞 Noon Square 前", type: "傳統甜食",
    dishes: ["龍鬚糖／꿀타래"], solo: "◎ 小吃友善", soloLevel: "good",
    note: "近期資料指向 Noon Square 正前方黃色攤位；街頭攤販不保證每日出現。找不到時可改去明洞 8 街 37-4 的固定原祖龍鬚糖店。", query: "명동 눈스퀘어 꿀타래", sourceUrl: "https://big5chinese.visitkorea.or.kr/svc/whereToGo/locIntrdn/rgnContentsView.do?vcontsId=91301",
  },
  {
    name: "保承會館 首爾新村店", korean: "보승회관 서울신촌점", area: "新村", type: "湯飯",
    dishes: ["豬肉湯飯", "醒酒湯", "一人套餐"], solo: "◎ 獨食友善", soloLevel: "good",
    note: "一人一碗且資料顯示設有獨食區；住新村／弘大附近時最順路。", query: "보승회관 서울신촌점", naverUrl: "https://naver.me/Gq84IiNp",
  },
  {
    name: "Artist Bakery 安國", korean: "아티스트베이커리 안국", area: "安國", type: "麵包",
    dishes: ["鹽麵包"], solo: "— 非正餐", soloLevel: "snack",
    note: "影片的首爾鹽麵包 #1；適合外帶，熱門時段可能排隊。", query: "아티스트베이커리 안국", naverUrl: "https://naver.me/5UEc0uzr",
  },
  {
    name: "益善愛意", korean: "익선애뜻", area: "益善洞", type: "餐廳",
    dishes: ["韓式料理"], solo: "△ 先確認", soloLevel: "maybe",
    note: "影片的益善洞用餐點；一人入座與菜單份量出發前再確認。", query: "익선애뜻", naverUrl: "https://naver.me/5ne4fnn0",
  },
  {
    name: "自然島鹽麵包", korean: "자연도소금빵&자연도가", area: "益善洞", type: "麵包",
    dishes: ["鹽麵包"], solo: "— 非正餐", soloLevel: "snack",
    note: "影片的首爾鹽麵包 #2；適合單買外帶。", query: "자연도소금빵 자연도가 익선", naverUrl: "https://naver.me/FTXw42uI",
  },
  {
    name: "Teafference Seoul", korean: "티퍼런스서울", area: "益善洞", type: "茶飲／咖啡",
    dishes: ["茶飲", "甜點"], solo: "◎ 一人進店", soloLevel: "good",
    note: "適合逛街途中一人休息；不能取代正餐。", query: "티퍼런스서울", naverUrl: "https://naver.me/GRo4vMgk",
  },
  {
    name: "당근당근", korean: "당근당근", area: "鐘路", type: "咖啡／甜點",
    dishes: ["咖啡", "甜點"], solo: "◎ 一人進店", soloLevel: "good",
    note: "影片西巡邏街路線的休息點；最新菜單請看店家頁。", query: "당근당근 종로", naverUrl: "https://naver.me/FoIcWDGq",
  },
  {
    name: "鐘三肉", korean: "종삼육", area: "鐘路三街", type: "烤肉",
    dishes: ["海鷗肉", "韓式烤肉"], solo: "△ 最低份數", soloLevel: "maybe",
    note: "位於海鷗肉街一帶；一人用餐須先確認最低點餐份數。", query: "종삼육", naverUrl: "https://naver.me/GvcTor7A",
  },
  {
    name: "屋同食", korean: "옥동식", area: "合井／弘大", type: "豬肉湯飯",
    dishes: ["豬肉湯飯"], solo: "◎ 獨食友善", soloLevel: "good",
    note: "一人一碗，適合獨食；熱門時段可能需要候位。", query: "옥동식", naverUrl: "https://naver.me/GOPeFGkr",
  },
  {
    name: "Salt Bread 延南店", korean: "솔트빵 연남점", area: "延南洞", type: "麵包",
    dishes: ["鹽麵包"], solo: "— 非正餐", soloLevel: "snack",
    note: "適合一人外帶，和 Butter & Shelter 二選一即可。", query: "솔트빵 연남점", naverUrl: "https://naver.me/GMPzL5oL",
  },
  {
    name: "Butter & Shelter 延南", korean: "버터앤쉘터 연남점", area: "延南洞", type: "麵包",
    dishes: ["鹽麵包", "烘焙點心"], solo: "— 非正餐", soloLevel: "snack",
    note: "影片的首爾鹽麵包 #3；適合外帶。", query: "버터앤쉘터 연남점", naverUrl: "https://naver.me/GMmgIvZg",
  },
  {
    name: "ASTERUM 433-10", korean: "ASTERUM 433-10", area: "弘大／延南", type: "主題咖啡",
    dishes: ["咖啡", "主題飲品"], solo: "◎ 一人進店", soloLevel: "good",
    note: "PLAVE 粉絲向咖啡空間；非粉絲不必特地排。", query: "ASTERUM 433-10", naverUrl: "https://naver.me/FN7XxwSG",
  },
  {
    name: "吃草的豬", korean: "풀뜯는 돼지", area: "弘大／延南", type: "烤肉",
    dishes: ["韓式豬肉燒烤"], solo: "△ 先確認", soloLevel: "maybe",
    note: "尚未找到可靠的一人最低份數規則；不要把它當唯一晚餐備案。", query: "풀뜯는 돼지", naverUrl: "https://naver.me/GBFHNoZY",
  },
  {
    name: "狀元飯卷 瑞草店", korean: "장원김밥 서초점", area: "瑞草", type: "飯卷",
    dishes: ["紫菜飯卷"], solo: "◎ 獨食友善", soloLevel: "good",
    note: "飯卷適合一人吃，但若沒有江南／瑞草行程不必為它跨區。", query: "장원김밥 서초점", naverUrl: "https://naver.me/GXAp5Mzf",
  },
  {
    name: "BETON 聖水", korean: "베통 성수", area: "聖水", type: "麵包",
    dishes: ["鹽麵包"], solo: "— 非正餐", soloLevel: "snack",
    note: "影片的首爾鹽麵包 #4；與 ETRE 擇一。", query: "베통 성수", naverUrl: "https://naver.me/FQVGKBbb",
  },
  {
    name: "ETRE BAKE HOUSE", korean: "에트레베이크하우스", area: "聖水", type: "麵包",
    dishes: ["鹽麵包", "烘焙點心"], solo: "— 非正餐", soloLevel: "snack",
    note: "影片的首爾鹽麵包 #5；也出現在老饕清單，與 BETON 擇一。", query: "에트레베이크하우스", naverUrl: "https://naver.me/GG7tTnpx", collectionTag: "#老饕",
  },
  {
    name: "清燉豬肉湯 Hau 聖水總店", korean: "돼지공탕 하우 성수본점", area: "聖水", type: "豬肉清湯",
    dishes: ["清燉豬肉湯", "冷製豬肉"], solo: "◎ 獨食友善", soloLevel: "good",
    note: "一人份湯飯並有一人座；冷製豬肉可選半份或不點。", query: "돼지공탕 하우 성수본점", naverUrl: "https://naver.me/5gF97LZu",
  },
  {
    name: "陵洞水芹菜 聖水店", korean: "능동미나리 성수점", area: "聖水", type: "水芹菜韓食",
    dishes: ["水芹菜生牛肉拌飯 ₩15,000", "特製水芹菜牛肉湯飯 ₩25,000"], solo: "◎ 獨食友善", soloLevel: "good",
    note: "影片二刷指數 6／5；拌飯與湯飯都能一人點。熱門時段可能候位，影片價格僅供預算參考。", query: "능동미나리 성수점", naverUrl: "https://naver.me/5iTdPV9Z", collectionTag: "#肥波",
  },
  {
    name: "江南 곱", korean: "곱 강남점", area: "江南", type: "韓牛烤腸",
    dishes: ["綜合拼盤 ₩25,000", "韓牛大腸 ₩26,000"], solo: "△ 最低份數", soloLevel: "maybe",
    note: "影片二刷指數 5／5；烤腸通常以多人與多份點餐較合適，先確認最低份數。", query: "곱 강남점 역삼로3길 12", naverUrl: "https://naver.me/53lKPDmz", collectionTag: "#肥波",
  },
  {
    name: "Gaksi Bossam", korean: "각시보쌈", area: "合井", type: "白切肉／菜包肉",
    dishes: ["白切肉套餐 ₩32,000"], solo: "△ 適合分享", soloLevel: "maybe",
    note: "影片二刷指數 6／5；合井站附近，影片選的套餐較適合兩人以上。若獨食可現場查看一人定食。", query: "각시보쌈 성지길 25", naverUrl: "https://naver.me/FW6hFU0x", collectionTag: "#肥波",
  },
  {
    name: "Pizzeria Marione", korean: "마리오네", area: "聖水", type: "拿坡里披薩",
    dishes: ["Mortadella Pistachio ₩28,000", "Margherita Classica ₩22,000"], solo: "△ 適合分享", soloLevel: "maybe",
    note: "影片二刷指數 6／5；兩款披薩適合多人分食，熱門時段先查候位方式。", query: "마리오네 성수", naverUrl: "https://naver.me/5bVsX7PR", collectionTag: "#肥波",
  },
  {
    name: "夢炭", korean: "몽탄", area: "三角地／龍山", type: "稻草燒肉",
    dishes: ["稻燒牛肋 ₩64,000", "稻燒松阪豬 ₩17,000", "泡菜炒飯 ₩5,000"], solo: "△ 聚餐較適合", soloLevel: "maybe",
    note: "影片二刷指數 6／5；三角地熱門燒肉店，主菜份量與候位方式較適合兩人以上事先規劃。", query: "몽탄 백범로99길 50", naverUrl: "https://naver.me/5eGT08VK", collectionTag: "#肥波",
  },
  {
    name: "Kkubdang 聖水店", korean: "꿉당 성수점", area: "聖水", type: "熟成豬肉燒烤",
    dishes: ["熟成梅花肉 ₩19,000", "熟成五花肉 ₩19,000", "熟成豬頰肉 ₩20,000"], solo: "△ 最低份數", soloLevel: "maybe",
    note: "影片二刷指數 5／5；現場候位可能很長，抵達聖水後先登記。燒肉通常需多份起點。", query: "꿉당 성수점", naverUrl: "https://naver.me/FZ275oxv", collectionTag: "#肥波",
  },
  {
    name: "Anju Maeul", korean: "안주마을", area: "西村／景福宮", type: "海鮮居酒屋",
    dishes: ["東海甜蝦刺身 ₩28,000", "生魷魚刺身 ₩28,000"], solo: "△ 酒館／候位", soloLevel: "maybe",
    note: "影片二刷指數 5／5；景福宮站旁的熱門海鮮酒館，季節菜色與候位變動大，適合兩人分享。", query: "안주마을 자하문로1길 3", naverUrl: "https://naver.me/5oE5C2uX", collectionTag: "#肥波",
  },
  {
    name: "Chowon", korean: "초원", area: "三角地／龍山", type: "韓牛／牛舌",
    dishes: ["韓牛霜降 ₩48,000", "特級牛舌 ₩36,000"], solo: "△ 聚餐較適合", soloLevel: "maybe",
    note: "影片二刷指數 5／5；位於三角地一帶，價位與燒肉形式較適合兩人以上分享。", query: "초원 한강대로80길 7", naverUrl: "https://naver.me/5CW7z1aV", collectionTag: "#肥波",
  },
  {
    name: "Asoto", korean: "아소토", area: "合井", type: "日式居酒屋",
    dishes: ["青甘韭菜捲 ₩17,000", "起司酪梨生魚丁 ₩18,000", "鹽烤雞頸肉 ₩17,000"], solo: "△ 一人一杯酒", soloLevel: "maybe",
    note: "影片二刷指數 6／5；有吧台但屬酒館，近期資料顯示一人一杯酒，想吃多款菜仍以兩人同行較合適。", query: "아소토 독막로2길 34", naverUrl: "https://naver.me/GyYbPxng", collectionTag: "#肥波",
  },
  {
    name: "Cham Mat 馬鈴薯排骨湯", korean: "참맛감자탕", area: "藥水", type: "馬鈴薯排骨湯",
    dishes: ["馬鈴薯排骨湯"], solo: "△ 先確認份量", soloLevel: "maybe",
    note: "老饕清單重點推薦；提供營業時間為 09:30–24:00。鍋物可能適合分享，先查看是否有一人份。", query: "참맛감자탕 다산로 107", collectionTag: "#老饕",
  },
  {
    name: "望遠洞豬肉湯飯", korean: "망원동돼지국밥", area: "望遠", type: "豬肉湯飯",
    dishes: ["豬肉湯飯"], solo: "◎ 獨食友善", soloLevel: "good",
    note: "一人一碗；提供營業時間為 07:00–22:00，週日到 16:00。", query: "망원동돼지국밥 동교로9길 71", collectionTag: "#老饕",
  },
  {
    name: "Portrait Coffee Bar", korean: "Portrait Coffee Bar", area: "望遠", type: "咖啡",
    dishes: ["咖啡"], solo: "◎ 一人進店", soloLevel: "good",
    note: "望遠散步休息點；提供營業時間為 10:00–22:00。", query: "Portrait Coffee Bar 포은로8길 32", collectionTag: "#老饕",
  },
  {
    name: "Eulji Butcher's Shop", korean: "을지정육", area: "乙支路三街", type: "熟成豬肩肉",
    dishes: ["烤豬肩肉", "方塊豬五花"], solo: "△ 最低份數", soloLevel: "maybe",
    note: "老饕清單重點推薦；提供營業時間為 13:00–22:30，燒肉較適合多人。", query: "을지정육 충무로5길 24", collectionTag: "#老饕",
  },
  {
    name: "Eulji FM", korean: "을지FM", area: "乙支路三街", type: "LP 酒吧",
    dishes: ["酒類", "酒吧小食"], solo: "◎ 一人喝酒", soloLevel: "good",
    note: "老饕清單重點推薦；週一公休，其他日期營業至深夜，當日時間請再確認。", query: "을지FM 충무로5길 26", collectionTag: "#老饕",
  },
  {
    name: "Yudak Story 新村店", korean: "유닭스토리 닭한마리 신촌점", area: "新村", type: "一隻雞",
    dishes: ["一隻雞鍋"], solo: "△ 適合分享", soloLevel: "maybe",
    note: "提供營業時間為 11:00–22:00；整鍋較適合兩人以上。", query: "유닭스토리 연세로4길 7", collectionTag: "#老饕",
  },
  {
    name: "Meokgeori 牛腸", korean: "먹거리양곱창", area: "新沙", type: "烤牛腸",
    dishes: ["烤牛腸"], solo: "△ 聚餐較適合", soloLevel: "maybe",
    note: "老饕清單重點推薦；提供營業時間為 15:30–23:00、週日公休。", query: "먹거리양곱창 잠원동 22-1", collectionTag: "#老饕",
  },
  {
    name: "Sogeukjeok 漢南本店", korean: "소극적 한남본점", area: "漢南", type: "生牛肉／酒館",
    dishes: ["生牛肉", "季節生魚片"], solo: "△ 酒館型態", soloLevel: "maybe",
    note: "老饕清單重點推薦；提供營業時間為 17:00–03:00，深夜前往注意返程交通。", query: "소극적 한남본점 대사관로31길 7", collectionTag: "#老饕",
  },
  {
    name: "Rabbit Hole Burger 聖水", korean: "래빗홀버거 성수", area: "聖水", type: "手工漢堡",
    dishes: ["手工漢堡", "薯條"], solo: "◎ 獨食友善", soloLevel: "good",
    note: "老饕清單重點推薦；部分近期資料互相衝突，出發前務必在 Naver 確認是否仍營業。", query: "래빗홀버거 성수 상원1길 35-23", collectionTag: "#老饕",
  },
  {
    name: "Choyeon BBQ", korean: "초연", area: "乙支路三街", type: "煙燻烤肉",
    dishes: ["煙燻烤肉", "兔子五花肉"], solo: "△ 最低份數", soloLevel: "maybe",
    note: "提供平日 11:00–22:30、週末 15:00 開始；燒肉較適合多人。", query: "초연 수표로 50", collectionTag: "#老饕",
  },
  {
    name: "Dong Hwa 食堂", korean: "동화식당", area: "南大門", type: "辣燉白帶魚",
    dishes: ["辣燉白帶魚"], solo: "△ 先確認份數", soloLevel: "maybe",
    note: "老饕清單重點推薦；位於南大門白帶魚巷，提供營業時間為 07:00–21:00。", query: "동화식당 남대문시장길 18-8", collectionTag: "#老饕",
  },
  {
    name: "Jojo 刀削麵 聖水店", korean: "조조칼국수 성수점", area: "聖水", type: "蛤蜊刀削麵",
    dishes: ["蛤蜊刀削麵", "海鮮煎餅"], solo: "◎ 獨食友善", soloLevel: "good",
    note: "一人吃刀削麵方便；提供營業時間為 10:00–21:30，煎餅較適合分享。", query: "조조칼국수 성수점", collectionTag: "#老饕",
  },
  {
    name: "最好吃豬腳 東大門店", korean: "가장맛있는족발 동대문점", area: "東大門 DDP", type: "韓式豬腳",
    dishes: ["韓式豬腳"], solo: "△ 適合分享", soloLevel: "maybe",
    note: "提供地址為乙支路 44 街 12、營業時間 11:00–02:00；店名依地址推定，出發前再用地圖核對。", query: "가장맛있는족발 을지로44길 12", collectionTag: "#老饕",
  },
  {
    name: "橋村炸雞 東大門", korean: "교촌치킨 동대문", area: "東大門 DDP", type: "韓式炸雞",
    dishes: ["醬油炸雞", "辣味炸雞"], solo: "△ 適合分享", soloLevel: "maybe",
    note: "原清單沒有提供分店地址；先以東大門區域搜尋，確認分店後再導航。", query: "교촌치킨 동대문", collectionTag: "#老饕",
  },
  {
    name: "Gyelim 辣雞湯", korean: "계림 종로본점", area: "乙支路／鐘路", type: "蒜香辣雞湯",
    dishes: ["辣雞湯／닭도리탕"], solo: "△ 鍋物分享", soloLevel: "maybe",
    note: "老饕清單重點推薦；提供週日公休與分段營業時間，整鍋適合多人。", query: "계림 종로본점 돈화문로4길 39", collectionTag: "#老饕",
  },
  {
    name: "Sancheong 炭火花園 乙支路", korean: "산청숯불가든 을지로", area: "乙支路三街", type: "炭火烤肉",
    dishes: ["炭火烤肉"], solo: "△ 最低份數", soloLevel: "maybe",
    note: "老饕清單重點推薦；提供營業時間為 11:30–23:00，近期頁面時間略有差異，當日再查。", query: "산청숯불가든 을지로", collectionTag: "#老饕",
  },
  {
    name: "肉烤冷麵 弘大 2 號店", korean: "육쌈냉면 홍대2호점", area: "弘大／延南", type: "冷麵",
    dishes: ["烤肉冷麵"], solo: "◎ 獨食友善", soloLevel: "good",
    note: "金針菇影片 02:12 的韓國夏日必吃 no.1；一人一碗，適合弘大逛街時消暑。", query: "육쌈냉면 홍대2호점 와우산로23길 35", naverUrl: "https://naver.me/xgXZ11Eq", collectionTag: "#金針菇",
  },
  {
    name: "浦項水拌生魚片", korean: "포항물회", area: "恩平", type: "水拌生魚片",
    dishes: ["辣味水拌生魚片／물회"], solo: "◎ 一人一碗", soloLevel: "good",
    note: "金針菇影片 05:52；冰涼湯底帶辣，怕生食或腸胃敏感者先評估。", query: "포항물회 통일로66길 6", naverUrl: "https://naver.me/xy7Kx4Fh", collectionTag: "#金針菇",
  },
  {
    name: "蓬坪蕎麥村 弘濟店", korean: "봉평메밀촌 홍제점", area: "弘濟／西大門", type: "涼粉湯",
    dishes: ["橡實涼粉湯"], solo: "◎ 獨食友善", soloLevel: "good",
    note: "金針菇影片 10:22；清爽的一人份夏日料理，可接西大門或弘濟一帶。", query: "봉평메밀촌 홍제점 통일로39가길 27", naverUrl: "https://naver.me/FLER0cNZ", collectionTag: "#金針菇",
  },
  {
    name: "鐵鍋一隻雞 北加佐店", korean: "가마솥 닭한마리 북가좌점", area: "北加佐／西大門", type: "醋雞麵",
    dishes: ["夏日限定醋雞麵"], solo: "◎ 麵食友善", soloLevel: "good",
    note: "金針菇影片 16:06；影片標為夏日限定，九月是否仍供應需先向店家確認。", query: "가마솥 닭한마리 북가좌점 응암로 76", naverUrl: "https://naver.me/FwGegIY6", collectionTag: "#金針菇",
  },
  {
    name: "五季南原泥鰍湯", korean: "오계절 남원추어탕", area: "延禧／西大門", type: "泥鰍湯",
    dishes: ["南原式泥鰍湯"], solo: "◎ 獨食友善", soloLevel: "good",
    note: "金針菇影片 18:23 形容為鰻魚的 CP 值版本；一人湯飯，適合延禧洞附近。", query: "오계절 남원추어탕 연희로 267", naverUrl: "https://naver.me/FpwTLkVL", collectionTag: "#金針菇",
  },
  {
    name: "麵首爾", korean: "면서울", area: "狎鷗亭羅德奧", type: "韓式麵食",
    dishes: ["生紫蘇油麵", "辣拌麵", "蕨菜芝麻麵"], solo: "◎ 獨食友善", soloLevel: "good",
    note: "黑白大廚金度潤主廚的單點麵店；地址為江南區宣陵路 805。近期以現場候位為主，出發前重查規則。", query: "면서울 선릉로 805", sourceUrl: "https://guide.michelin.com/kr/ko/seoul-capital-area/kr-seoul/restaurant/myeon-seoul",
  },
  {
    name: "PURADAK Chicken", korean: "푸라닭 치킨", area: "首爾各區", type: "韓式炸雞連鎖",
    dishes: ["Black Aglio 黑蒜醬油炸雞", "Gochu Mayo 辣椒美乃滋炸雞"], solo: "△ 適合分享", soloLevel: "maybe",
    note: "韓國連鎖炸雞品牌，口味選擇多；建議依住宿或當天行程找最近分店，不需要為炸雞跨區。多人可點不同口味分享，一人則留意整雞份量。", query: "푸라닭 치킨 서울", sourceUrl: "https://puradakchicken.com/main/",
  },
  {
    name: "Yankee Tongdak", korean: "양키통닭", area: "文來洞", type: "柴火烤雞",
    dishes: ["原味菠菜烤雞", "胡椒奶油烤雞"], solo: "△ 聚餐較適合", soloLevel: "maybe",
    note: "招牌以橡木柴火烤雞搭配炒菠菜與整顆蒜頭；本店資料指向永登浦區道林路 139 街 13。整隻雞適合 2–3 人分享，熱門晚餐時段可能長候位。", query: "양키통닭 도림로139길 13", sourceUrl: "https://www.diningcode.com/profile.php?rid=5jd7lDjE5yZ5",
  },
  {
    name: "酥脆馬車 84", korean: "바삭마차", area: "望遠市場 84", type: "炸物／甜點",
    dishes: ["烤棉花糖冰淇淋", "炸起司莫札瑞拉豬排"], solo: "△ 高負擔", soloLevel: "maybe",
    note: "主食與甜食都偏重；豬排、冰淇淋不要同時再疊其他炸物。", query: "망원시장 바삭마차 84",
  },
  {
    name: "勳勳糖餅 68", korean: "훈훈호떡", area: "望遠市場 68", type: "市場甜食",
    dishes: ["糖餅"], solo: "◎ 小吃友善", soloLevel: "good",
    note: "單份甜食首選；現做溫度很高，食用時小心。老饕清單提供 11:00–20:30、週一公休。", query: "망원시장 훈훈호떡 68", collectionTag: "#老饕",
  },
  {
    name: "雨耳樂 37", korean: "우이락", area: "望遠市場 37", type: "市場小吃",
    dishes: ["青陽辣椒鑲肉"], solo: "△ 份量注意", soloLevel: "maybe",
    note: "可一人買，但建議和炸雞丁、年糕排骨三選一。", query: "망원시장 우이락 37",
  },
  {
    name: "QS 炸雞丁 48", korean: "큐스닭강정", area: "望遠市場 48", type: "炸雞",
    dishes: ["韓式辣醬炸雞丁", "蒜辣醬油炸雞丁"], solo: "△ 份量注意", soloLevel: "maybe",
    note: "外帶容易，但一盒可能會吃不下後續攤位。", query: "망원시장 큐스닭강정 48",
  },
  {
    name: "望遠年糕排骨 62", korean: "망원떡갈비", area: "望遠市場 62", type: "市場小吃",
    dishes: ["年糕排骨"], solo: "◎ 小吃友善", soloLevel: "good",
    note: "適合單點；影片提醒已從 38 號搬到 62 號，出發前再核對。", query: "망원시장 망원떡갈비 62",
  },
  {
    name: "棒錘手工麵 58", korean: "바프로 손수제비", area: "望遠市場 58", type: "麵食",
    dishes: ["手工湯麵", "炸醬麵", "紫蘇拌麵"], solo: "◎ 正餐友善", soloLevel: "good",
    note: "必須一人一份；選它作主食就不要再點炸起司豬排。老饕清單提供 10:00–20:30。", query: "망원시장 바프로 손수제비 58", collectionTag: "#老饕",
  },
  {
    name: "望遠咖啡", korean: "카페망원", area: "望遠市場", type: "咖啡",
    dishes: ["咖啡", "可攜外食"], solo: "◎ 一人休息", soloLevel: "good",
    note: "可作為坐下吃市場外帶食物的基地；外食規則出發前再確認。", query: "카페망원 망원시장",
  },
  {
    name: "望遠可樂餅 01", korean: "망원고로케", area: "望遠市場 01", type: "市場小吃",
    dishes: ["咖哩可樂餅", "紅豆甜甜圈"], solo: "◎ 小吃友善", soloLevel: "good",
    note: "鹹、甜擇一，不需要和糖餅都買現吃。", query: "망원시장 망원고로케 01",
  },
  {
    name: "훈훈 小飯卷", korean: "훈훈꼬마김밥", area: "望遠市場", type: "飯卷",
    dishes: ["招牌蔬菜飯卷"], solo: "◎ 小吃友善", soloLevel: "good",
    note: "可作較輕主食，也適合外帶。", query: "망원시장 훈훈꼬마김밥",
  },
  {
    name: "Ugly Bakery", korean: "아글빵집", area: "望遠", type: "麵包",
    dishes: ["猛瑪包", "藍莓冰奶油麵包"], solo: "— 非正餐", soloLevel: "snack",
    note: "適合外帶或伴手禮；熱門時段可能排隊。", query: "아글빵집 망원",
  },
  {
    name: "Stereo Phonic 音響咖啡", korean: "Stereo Phonic", area: "弘大／延南", type: "音響咖啡",
    dishes: ["咖啡", "音樂聆聽空間"], solo: "◎ 一人進店", soloLevel: "good",
    note: "適合逛弘大、延南途中一人休息；店名、低消與當日營業時間以 Naver Place 為準。", query: "Stereo Phonic 연남", naverUrl: "https://naver.me/5A3p6w4D", collectionTag: "#陪沈團",
  },
  {
    name: "Darak Two 刀削麵", korean: "다락투", area: "弘大／延南", type: "刀削麵",
    dishes: ["韓式刀削麵"], solo: "◎ 獨食友善", soloLevel: "good",
    note: "一人一碗的麵食選項，適合做弘大正餐；出發前確認休息時間與是否需要候位。", query: "다락투 홍대", naverUrl: "https://naver.me/GctrjXOV", collectionTag: "#陪沈團",
  },
  {
    name: "鮮奶油草莓蛋糕收藏", korean: "생크림 딸기 케이크", area: "弘大／延南", type: "蛋糕／甜點",
    dishes: ["鮮奶油草莓蛋糕"], solo: "— 非正餐", soloLevel: "snack",
    note: "原分享未附店名文字，先以 Naver 原始收藏連結保留；草莓季、品項與是否售罄需當日確認。", query: "연남 생크림 딸기 케이크", naverUrl: "https://naver.me/FQVGs95n", collectionTag: "#陪沈團",
  },
  {
    name: "弘大生必吃炸物", korean: "홍대 튀김", area: "弘大／延南", type: "炸物小吃",
    dishes: ["韓式炸物"], solo: "◎ 小吃友善", soloLevel: "good",
    note: "原分享未附店名文字，保留 Naver 店家連結；適合當小吃，不建議和炸雞排成同一餐。", query: "홍대 튀김", naverUrl: "https://naver.me/x7ndoV8F", collectionTag: "#陪沈團",
  },
  {
    name: "朋友年輕批貨時愛吃的韓料", korean: "한식집 위치 참고", area: "弘大／延南", type: "韓式料理",
    dishes: ["韓式料理"], solo: "△ 店址待確認", soloLevel: "maybe",
    note: "重要：Naver 連結指向的是地標，目標餐廳在其對面，不是連結本身。出發前需請推薦者補店名或現場核對招牌。", query: "홍대 한식", naverUrl: "https://naver.me/FbqQ1Lch", collectionTag: "#陪沈團",
  },
  {
    name: "海洋會之愛 延南店", korean: "바다회사랑 연남점", area: "弘大／延南", type: "生魚片",
    dishes: ["季節生魚片", "海鮮"], solo: "△ 適合分享", soloLevel: "maybe",
    note: "生魚片份量通常適合多人分享；熱門季節與晚餐時段可能候位，當日魚種與價格以店內為準。", query: "바다회사랑 연남점", naverUrl: "https://naver.me/xBwJE9fI", collectionTag: "#陪沈團",
  },
  {
    name: "風川烤鰻 延南店", korean: "풍천장어 연남점", area: "弘大／延南", type: "烤鰻魚",
    dishes: ["風川烤鰻"], solo: "△ 先確認份數", soloLevel: "maybe",
    note: "較適合聚餐；一人用餐前先確認最低點餐份數與烤鰻計價方式。影片收藏的白燒鰻魚套餐為 ₩78,000。", query: "풍천장어 연남점", naverUrl: "https://naver.me/FBe2dOpb", collectionTag: "#陪沈團 #肥波",
  },
  {
    name: "煎餅咚咚酒", korean: "주전막걸리아노", area: "弘大／延南", type: "煎餅／米酒",
    dishes: ["韓式煎餅", "馬格利米酒"], solo: "△ 聚餐較適合", soloLevel: "maybe",
    note: "煎餅與整壺米酒較適合兩人以上分享；韓文店名依分享文字暫錄，請以 Naver 店家頁顯示為準。", query: "주전막걸리아노 홍대", naverUrl: "https://naver.me/xAFCcdWH", collectionTag: "#陪沈團",
  },
  {
    name: "雞匠紫菜飯卷 弘大店", korean: "닭장수김밥 홍대점", area: "弘大／延南", type: "健康飯卷",
    dishes: ["健康紫菜飯卷"], solo: "◎ 獨食友善", soloLevel: "good",
    note: "份量與形式適合一人快速用餐，也可外帶當移動餐。", query: "닭장수김밥 홍대점", naverUrl: "https://naver.me/FhUL9BjF", collectionTag: "#陪沈團",
  },
];

export const hongdaeSaves = [
  { name: "Stereo Phonic 音響咖啡", korean: "Stereo Phonic", category: "咖啡", note: "音響與咖啡空間，適合一人休息。", query: "Stereo Phonic 연남", naverUrl: "https://naver.me/5A3p6w4D" },
  { name: "Darak Two 刀削麵", korean: "다락투", category: "美食", note: "一人一碗，適合作弘大正餐。", query: "다락투 홍대", naverUrl: "https://naver.me/GctrjXOV" },
  { name: "鮮奶油草莓蛋糕", korean: "생크림 딸기 케이크", category: "甜點", note: "原分享未附店名，直接保留 Naver 收藏；先確認季節供應。", query: "연남 생크림 딸기 케이크", naverUrl: "https://naver.me/FQVGs95n", pending: true },
  { name: "YESEYESEE", korean: "예스아이씨", category: "男裝", note: "男生街頭服飾收藏，先看當季款式與尺寸。", query: "예스아이씨 홍대", naverUrl: "https://naver.me/FA2lJoGE" },
  { name: "弘大生必吃炸物", korean: "홍대 튀김", category: "小吃", note: "原分享未附店名，使用 Naver 收藏直接導航。", query: "홍대 튀김", naverUrl: "https://naver.me/x7ndoV8F", pending: true },
  { name: "豬爸媽汗蒸幕", korean: "돼지엄마 찜질방", category: "汗蒸幕", note: "汗蒸幕收藏；前往前確認入場、過夜與行李規則。", query: "돼지엄마 찜질방 홍대", naverUrl: "https://naver.me/xFLuqHQA" },
  { name: "朋友愛吃的韓料", korean: "한식집 위치 참고", category: "美食", note: "連結只是地標，餐廳在其對面；尚缺正式店名，勿直接把連結目的地當餐廳。", query: "홍대 한식", naverUrl: "https://naver.me/FbqQ1Lch", pending: true },
  { name: "Little Riddle Store", korean: "리틀리들 스토어", category: "選物", note: "適合逛小物與趣味雜貨。", query: "Little Riddle Store 연남", naverUrl: "https://naver.me/57VZUZHx" },
  { name: "海洋會之愛 延南店", korean: "바다회사랑 연남점", category: "美食", note: "季節生魚片，較適合多人分享。", query: "바다회사랑 연남점", naverUrl: "https://naver.me/xBwJE9fI" },
  { name: "風川烤鰻 延南店", korean: "풍천장어 연남점", category: "美食", note: "聚餐烤鰻；先確認最低點餐份數。", query: "풍천장어 연남점", naverUrl: "https://naver.me/FBe2dOpb" },
  { name: "Mono Mansion 弘大店", korean: "모노맨션 홍대점", category: "拍貼", note: "逛街途中拍貼留念，尖峰時段可能排隊。", query: "모노맨션 홍대점", naverUrl: "https://naver.me/x67o329R" },
  { name: "煎餅咚咚酒", korean: "주전막걸리아노", category: "美食", note: "煎餅配馬格利，兩人以上較好分食。", query: "주전막걸리아노 홍대", naverUrl: "https://naver.me/xAFCcdWH" },
  { name: "雞匠紫菜飯卷 弘大店", korean: "닭장수김밥 홍대점", category: "美食", note: "健康飯卷，適合獨食或外帶。", query: "닭장수김밥 홍대점", naverUrl: "https://naver.me/FhUL9BjF" },
];

export const feiboSaves = [
  { name: "陵洞水芹菜 聖水店", korean: "능동미나리 성수점", area: "聖水", timecode: "00:20", rating: "6／5", menu: ["水芹菜生牛肉拌飯 ₩15,000", "特製水芹菜牛肉湯飯 ₩25,000"], query: "능동미나리 성수점", naverUrl: "https://naver.me/5iTdPV9Z" },
  { name: "江南 곱", korean: "곱 강남점", area: "江南", timecode: "02:53", rating: "5／5", menu: ["綜合拼盤 ₩25,000", "韓牛大腸 ₩26,000"], query: "곱 강남점", naverUrl: "https://naver.me/53lKPDmz" },
  { name: "Gaksi Bossam", korean: "각시보쌈", area: "合井", timecode: "05:38", rating: "6／5", menu: ["白切肉套餐 ₩32,000"], query: "각시보쌈", naverUrl: "https://naver.me/FW6hFU0x" },
  { name: "Pizzeria Marione", korean: "마리오네", area: "聖水", timecode: "08:03", rating: "6／5", menu: ["Mortadella Pistachio ₩28,000", "Margherita Classica ₩22,000"], query: "마리오네 성수", naverUrl: "https://naver.me/5bVsX7PR" },
  { name: "夢炭", korean: "몽탄", area: "三角地", timecode: "10:29", rating: "6／5", menu: ["稻燒牛肋 ₩64,000", "稻燒松阪豬 ₩17,000", "泡菜炒飯 ₩5,000"], query: "몽탄", naverUrl: "https://naver.me/5eGT08VK" },
  { name: "Kkubdang 聖水店", korean: "꿉당 성수점", area: "聖水", timecode: "14:07", rating: "5／5", menu: ["熟成梅花肉 ₩19,000", "熟成五花肉 ₩19,000", "熟成豬頰肉 ₩20,000"], query: "꿉당 성수점", naverUrl: "https://naver.me/FZ275oxv" },
  { name: "Anju Maeul", korean: "안주마을", area: "西村", timecode: "17:04", rating: "5／5", menu: ["東海甜蝦刺身 ₩28,000", "生魷魚刺身 ₩28,000"], query: "안주마을", naverUrl: "https://naver.me/5oE5C2uX" },
  { name: "Chowon", korean: "초원", area: "三角地", timecode: "19:42", rating: "5／5", menu: ["韓牛霜降 ₩48,000", "特級牛舌 ₩36,000"], query: "초원 한강대로80길 7", naverUrl: "https://naver.me/5CW7z1aV" },
  { name: "風川鰻魚 延南店", korean: "풍천장어 연남점", area: "延南", timecode: "22:29", rating: "5／5", menu: ["白燒鰻魚套餐 ₩78,000"], query: "풍천장어 연남점", naverUrl: "https://naver.me/5AmfnBTN" },
  { name: "Asoto", korean: "아소토", area: "合井", timecode: "24:59", rating: "6／5", menu: ["青甘韭菜捲 ₩17,000", "起司酪梨生魚丁 ₩18,000", "鹽烤雞頸肉 ₩17,000"], query: "아소토", naverUrl: "https://naver.me/GyYbPxng" },
];

export const laotaoSaves = [
  { name: "Cham Mat 馬鈴薯排骨湯", korean: "참맛감자탕", station: "藥水站", category: "美食", address: "서울 중구 다산로 107", hours: "09:30–24:00", note: "馬鈴薯排骨湯；鍋物份量先確認。", query: "참맛감자탕 다산로 107", recommended: true },
  { name: "棒錘手工刀削麵", korean: "바프로 손수제비", station: "望遠市場", category: "美食", address: "서울 마포구 망원동 414-26", hours: "10:00–20:30", note: "手工湯麵、炸醬麵、紫蘇拌麵；一人一份。", query: "바프로 손수제비 망원시장" },
  { name: "望遠洞豬肉湯飯", korean: "망원동돼지국밥", station: "望遠市場", category: "美食", address: "서울 마포구 동교로9길 71", hours: "07:00–22:00；週日至 16:00", note: "一人一碗的早午餐備案。", query: "망원동돼지국밥 동교로9길 71" },
  { name: "勳勳糖餅", korean: "훈훈호떡", station: "望遠市場", category: "小吃", address: "서울 마포구 포은로6길 25", hours: "11:00–20:30；週一休", note: "現做糖餅很燙，適合單份現吃。", query: "훈훈호떡 망원시장" },
  { name: "Portrait Coffee Bar", korean: "Portrait Coffee Bar", station: "望遠市場", category: "咖啡", address: "서울 마포구 포은로8길 32", hours: "10:00–22:00", note: "望遠散步途中休息。", query: "Portrait Coffee Bar 포은로8길 32" },
  { name: "Eulji Butcher's Shop", korean: "을지정육", station: "乙支路三街站", category: "美食", address: "서울 중구 충무로5길 24", hours: "13:00–22:30", note: "烤豬肩肉；燒肉較適合多人。", query: "을지정육 충무로5길 24", recommended: true },
  { name: "Eulji FM", korean: "을지FM", station: "乙支路三街站", category: "酒吧", address: "서울 중구 충무로5길 26 2층", hours: "18:30–02:00；週一休", note: "LP 音樂酒吧；週日提供時間至 00:30。", query: "을지FM 충무로5길 26", recommended: true },
  { name: "Yudak Story 一隻雞", korean: "유닭스토리 닭한마리 신촌점", station: "新村站", category: "美食", address: "서울 서대문구 연세로4길 7 1층", hours: "11:00–22:00", note: "整鍋較適合兩人以上。", query: "유닭스토리 닭한마리 신촌점" },
  { name: "Meokgeori 牛腸", korean: "먹거리양곱창", station: "新沙站", category: "美食", address: "서울 서초구 잠원동 22-1", hours: "15:30–23:00；週日休", note: "烤牛腸，較適合聚餐。", query: "먹거리양곱창 잠원동 22-1", recommended: true },
  { name: "Sogeukjeok 漢南本店", korean: "소극적 한남본점", station: "漢南站", category: "美食／酒吧", address: "서울 용산구 대사관로31길 7 2층", hours: "17:00–03:00", note: "生牛肉與酒館料理；留意深夜返程。", query: "소극적 한남본점", recommended: true },
  { name: "首爾東大門諾富特大使酒店及公寓", korean: "노보텔 앰배서더 서울 동대문", station: "東大門歷史文化公園站", category: "住宿", address: "서울 중구 을지로 238", hours: "入住規則以官方為準", note: "住宿備選；HafH 可作心得參考，訂房條件以官方／平台為準。", query: "노보텔 앰배서더 서울 동대문", sourceUrl: "https://all.accor.com/hotel/A5U6/index.en.shtml", extraUrl: "https://www.hafh.com/zh-tw" },
  { name: "Rabbit Hole Burger 聖水", korean: "래빗홀버거 성수", station: "聖水站", category: "美食", address: "서울 성동구 상원1길 35-23", hours: "提供資料為 11:00–20:00；週日休", note: "不同近期來源對營業狀態互相衝突，務必出發前查 Naver。", query: "래빗홀버거 성수", recommended: true, pending: true },
  { name: ".NOTE 香水工坊 聖水店", korean: "닷노트 성수", station: "聖水站", category: "體驗", address: "以 Naver 店家頁為準", hours: "需查看預約場次", note: "自製香水體驗；確認語言、時長與取消規則。", query: "닷노트 성수" },
  { name: "Choyeon BBQ", korean: "초연", station: "乙支路三街站", category: "美食", address: "서울 중구 수표로 50", hours: "11:00–22:30；週末 15:00 起", note: "煙燻烤肉，較適合多人。", query: "초연 수표로 50" },
  { name: "Dong Hwa 食堂", korean: "동화식당", station: "南大門市場", category: "美食", address: "서울 중구 남창동 34-146", hours: "07:00–21:00", note: "辣燉白帶魚；先確認一人份規則。", query: "동화식당 남대문시장", recommended: true },
  { name: "Jojo 刀削麵 聖水店", korean: "조조칼국수 성수점", station: "聖水站", category: "美食", address: "서울 성동구 성수일로8길 55 1층", hours: "10:00–21:30", note: "蛤蜊刀削麵適合獨食，煎餅適合分享。", query: "조조칼국수 성수점" },
  { name: "ETRE BAKE HOUSE", korean: "에트레베이크하우스", station: "聖水站", category: "麵包", address: "서울 성동구 연무장길 37-5", hours: "10:00–21:00", note: "海鹽麵包；也在影片鹽麵包收藏中。", query: "에트레베이크하우스", naverUrl: "https://naver.me/GG7tTnpx" },
  { name: "最好吃豬腳 東大門店", korean: "가장맛있는족발 동대문점", station: "東大門 DDP 站", category: "美食", address: "서울 중구 을지로44길 12", hours: "11:00–02:00", note: "店名依地址推定，出發前核對分店。", query: "가장맛있는족발 을지로44길 12", pending: true },
  { name: "橋村炸雞 東大門", korean: "교촌치킨 동대문", station: "東大門 DDP 站", category: "美食", address: "原清單未提供分店", hours: "待選定分店", note: "先以東大門區域搜尋，確認分店後再導航。", query: "교촌치킨 동대문", pending: true },
  { name: "Gyelim 辣雞湯", korean: "계림 종로본점", station: "乙支路站", category: "美食", address: "서울 종로구 돈화문로4길 39", hours: "11:30–15:30、16:30–21:45；週日休", note: "蒜香辣雞湯，整鍋適合多人。", query: "계림 종로본점", recommended: true },
  { name: "Sancheong 炭火花園 乙支路", korean: "산청숯불가든 을지로", station: "乙支路三街站", category: "美食", address: "서울 중구 을지로 114-6", hours: "提供資料為 11:30–23:00", note: "炭火烤肉；近期營業時間資料略有差異。", query: "산청숯불가든 을지로", recommended: true },
];

export const jinzhenguSaves = {
  food: [
    { name: "肉烤冷麵 弘大 2 號店", korean: "육쌈냉면 홍대2호점", area: "弘大", timecode: "02:12", detail: "韓國夏日必吃 no.1 冷麵", address: "서울 마포구 와우산로23길 35 2층", query: "육쌈냉면 홍대2호점", naverUrl: "https://naver.me/xgXZ11Eq" },
    { name: "浦項水拌生魚片", korean: "포항물회", area: "恩平", timecode: "05:52", detail: "辣味冰涼水拌生魚片", address: "서울 은평구 통일로66길 6 1층", query: "포항물회 통일로66길 6", naverUrl: "https://naver.me/xy7Kx4Fh" },
    { name: "蓬坪蕎麥村 弘濟店", korean: "봉평메밀촌 홍제점", area: "弘濟", timecode: "10:22", detail: "橡實涼粉湯", address: "서울 서대문구 통일로39가길 27", query: "봉평메밀촌 홍제점", naverUrl: "https://naver.me/FLER0cNZ" },
    { name: "鐵鍋一隻雞 北加佐店", korean: "가마솥 닭한마리 북가좌점", area: "北加佐", timecode: "16:06", detail: "夏日限定醋雞麵", address: "서울 서대문구 응암로 76 103호", query: "가마솥 닭한마리 북가좌점", naverUrl: "https://naver.me/FwGegIY6" },
    { name: "五季南原泥鰍湯", korean: "오계절 남원추어탕", area: "延禧", timecode: "18:23", detail: "鰻魚 CP 值版本的泥鰍湯", address: "서울 서대문구 연희로 267 2층", query: "오계절 남원추어탕", naverUrl: "https://naver.me/FpwTLkVL" },
  ],
  beauty: [
    { timecode: "01:37", name: "MEDIHEAL 精華面膜片", category: "面膜保養", note: "依膚況挑系列；多入組適合分送。" },
    { timecode: "03:25", name: "Biodance Collagen 面膜", category: "面膜保養", note: "長時間貼敷型產品，敏感肌先測試。" },
    { timecode: "04:14", name: "Beyond 美白乳液", category: "身體保養", note: "原文為 beyong，暫按 Beyond 品牌整理，現場核對品名。", pending: true },
    { timecode: "05:27", name: "YUNJAC 保濕底霜", category: "妝前保養", note: "確認質地是否適合自己的底妝與膚質。" },
    { timecode: "06:13", name: "OBgE 防曬棒", category: "防曬", note: "補擦方便；防曬係數與使用量以包裝為準。" },
    { timecode: "07:12", name: "The Saem 遮瑕", category: "底妝", note: "現場試色，避免只按影片色號購買。" },
    { timecode: "08:40", name: "About Tone Powder Pact", category: "定妝", note: "依膚色、乾油肌挑粉餅版本。" },
    { timecode: "09:55", name: "So Natural Fix 定妝噴霧", category: "定妝", note: "原文只寫 fix，暫按品牌定妝噴霧整理，現場核對。", pending: true },
    { timecode: "10:30", name: "CANMAKE 腮紅霜", category: "彩妝", note: "CANMAKE 是日本品牌；仍可在韓國購入，但不算韓國限定。" },
    { timecode: "11:38", name: "Fillimilli Cushion Pang Pang Puff", category: "美妝工具", note: "氣墊粉撲，適合自用或小禮物。" },
    { timecode: "12:43", name: "Too Cool For School 14", category: "彩妝", note: "缺少完整品名，保留影片標記 14，購買前核對品項與色號。", pending: true },
    { timecode: "14:09", name: "Peripera Mood Glowy Tint", category: "唇彩", note: "現場試色；色號名稱與販售狀態可能更新。" },
    { timecode: "15:14", name: "Banila Co 清潔霜", category: "卸妝清潔", note: "依膚質選版本，確認容量是否適合託運。" },
    { timecode: "16:29", name: "Teazen 康普茶", category: "飲品", note: "原文為 teaser，暫按韓國常見 Teazen 康普茶整理，現場核對。", pending: true },
  ],
};

export const threadsResearch = [
  {
    id: "spots", icon: "⌖", title: "首爾景點", subtitle: "冷門景點與分區玩法",
    source: "https://www.threads.com/@eiei_517/post/DXJ0ELyCVyK",
    items: [
      { name: "恩平韓屋村＋1인1잔", detail: "北漢山景觀咖啡；團體 Day 4 已到恩平，不必再排私人行程。", query: "은평한옥마을 1인1잔" },
      { name: "纛島漢江公園", detail: "可接黑膠咖啡與漢江風景，適合傍晚。", query: "뚝섬한강공원" },
      { name: "博物館群", detail: "中央博物館、戰爭紀念館、西大門刑務所，可依興趣選一館。", query: "국립중앙박물관" },
      { name: "德壽宮・大韓帝國歷史館", detail: "歷史館導覽需另查線上預約；可接市廳、明洞。", query: "덕수궁 대한제국역사관" },
      { name: "駱山公園＋大學路", detail: "爬坡看首爾夜景，下方有劇場、音樂劇與咖啡。", query: "낙산공원" },
      { name: "延禧洞／城北川／成均館", detail: "分別偏選物咖啡、散步與秋季銀杏；九月以延禧洞較容易順接西側路線。", query: "연희동" },
    ],
  },
  {
    id: "suwon", icon: "◇", title: "水原補充", subtitle: "團體行程的期待管理",
    source: "https://www.threads.com/@mmtraveltravel/post/DXZWzc4kxmo",
    items: [
      { name: "水原華城", detail: "UNESCO 城牆適合夕陽；本團 Day 5 已安排。", query: "수원화성" },
      { name: "熱氣球", detail: "升空條件受天候影響，若比賽日有空再查當日場次。", query: "플라잉수원" },
      { name: "水原炸雞", detail: "當地代表美食；網站水原美食區已有炸雞街選項。", query: "수원통닭거리" },
      { name: "Starfield 水原", detail: "星空圖書館被形容為升級版；團體 Day 5 已安排。", query: "스타필드 수원 별마당도서관" },
    ],
  },
  {
    id: "food", icon: "●", title: "網友美食", subtitle: "高互動貼文交叉收藏",
    source: "https://www.threads.com/@seoyeonlee.808/post/DbkwhoXk0a0",
    items: [
      { name: "首爾經典清單", detail: "土俗村、滿足五香豬腳、大瓦房醬蟹、Onion、順熙綠豆煎餅、河東館等；不要為打卡跨區，當天附近再選。", query: "서울 맛집" },
      { name: "實測前三名", detail: "龍山魚板 용산오뎅、法棍 바게티、聖水烤豬肉 꿉당；原貼文另推白切肉、平民韓食與西巡邏街 wine bar。", query: "용산오뎅" },
      { name: "弘大／聖水補充", detail: "弘大烤肉配冷麵、延南法式吐司、聖水陵洞水芹菜、吃草的豬。", query: "능동미나리 성수" },
      { name: "麵首爾", detail: "金度潤主廚的單點麵食，已加入上方黑白大廚與公開美食收藏。", query: "면서울 선릉로 805" },
    ],
  },
  {
    id: "fashion", icon: "▱", title: "服飾購物", subtitle: "以非精品優先排序",
    source: "https://www.threads.com/@frank.sie/post/DB72mxoSGa9",
    items: [
      { name: "先逛：Musinsa／Nomanual", detail: "弘大最順路；Musinsa 聖水大林倉庫可接聖水日。", query: "무신사 스탠다드 홍대" },
      { name: "再看：Worksout／8 Division", detail: "Worksout 有弘大分店；8 Division 可接明洞，不用專程跨區。", query: "웍스아웃 홍대" },
      { name: "品牌備忘", detail: "Ader Error 據網友稱週二補貨；另有 North Face White Label、Lee 韓國線、DEUS 首爾限定。", query: "아더에러 서울" },
      { name: "品質與退稅", detail: "網友建議不熟店家時優先百貨或免稅店，價格、品質與退稅流程較透明。", query: "더현대 서울" },
    ],
  },
  {
    id: "beauty", icon: "✦", title: "藥妝提醒", subtitle: "圖片清單未完整擷取",
    source: "https://www.threads.com/@lucy09.05/post/DZgjOSEEySr",
    items: [
      { name: "Olive Young 零食", detail: "貝果餅乾、炸海苔、魷魚條、德國結與低卡玉米片。", query: "올리브영 명동" },
      { name: "彩妝可試", detail: "Wakemake 08 色與 Olive Young 粉撲是留言推薦；仍應現場試色。", query: "올리브영 웨이크메이크" },
      { name: "藥局資訊要保守", detail: "網友貼文不等同醫療建議；藥品成分、適應症、處方與入境限制應問藥師並查官方規則。", query: "홍익약국" },
    ],
  },
  {
    id: "gifts", icon: "□", title: "零食伴手禮", subtitle: "適合多人分送",
    source: "https://www.threads.com/@yon__lin/post/DZ1xzdREjUO",
    items: [
      { name: "輕巧首選", detail: "原味／橄欖油／芥末／泡菜海苔、康普茶，體積小且容易分送。", query: "롯데마트 서울역점" },
      { name: "超市清單", detail: "Zero 糖果、Market O 布朗尼、Binch 抹茶、炸海苔、BR 黃豆粉巧克力派、HBAF 杏仁。", query: "롯데마트 서울역점" },
      { name: "便利商店", detail: "CU 杜拜巧克力、奶昔與咖啡糖屬網友話題品，庫存不保證。", query: "CU 편의점" },
      { name: "購買前翻背面", detail: "至少兩個獨立討論提醒檢查原產地，避免用高價買到非韓國製商品。", query: "롯데마트 서울역점" },
    ],
  },
];

const hotel = { name: "HOMES Stay Suwon", query: "홈즈스테이 수원", lat: 37.2636, lng: 127.0307 };
const venue = {
  name: "水原農業生命科學高中",
  query: "수원농생명과학고등학교 광교산로 13",
  note: "比賽場館 · 경기 수원시 장안구 광교산로 13",
  lat: 37.2933608,
  lng: 127.0202358,
  officialUrl: "https://sunong-h.goesw.kr/sunong-h/main.do",
};

export const days = [
  {
    id: 1, date: "09/11", weekday: "五", title: "抵達韓國 · 比賽練習", area: "仁川 → 水原",
    transport: "團體專車 · 機場 → 午餐 → 會場 → 晚餐 → 飯店",
    weatherNote: "出發前 7 天再確認天氣",
    summary: ["BR170", "團體專車", "三餐已含"],
    places: [
      { name: "仁川國際機場", query: "인천국제공항", lat: 37.4602, lng: 126.4407 },
      venue,
      hotel,
    ],
    events: [
      { time: "07:30", title: "桃園出發", subtitle: "長榮航空 BR170", type: "flight", meta: "桃園 T2 → 仁川 · 約 3 小時 30 分", confirmed: true },
      { time: "11:00", title: "抵達仁川國際機場", subtitle: "入境、領取行李後集合", type: "place", place: "仁川國際機場", confirmed: true },
      { time: "12:30", title: "原訂午餐 · 石鍋拌飯＋小火鍋", subtitle: "旅行社安排", type: "food", meta: "與 13:00 前抵達場館的通知幾乎沒有緩衝，需確認是否提前、改餐盒或調整安排。", estimate: true },
      { time: "13:00 前", title: "抵達比賽場地", subtitle: "水原農業生命科學高中", type: "place", meta: "13 Gwanggyosan-ro, Jangan-gu, Suwon-si, Gyeonggi-do", mapQuery: "수원농생명과학고등학교 광교산로 13", status: "比賽通知" },
      { time: "13:00–17:00", title: "全體練習", subtitle: "2026 韓國京畿道國際體操比賽", type: "activity", meta: "依比賽通知準時到場；實際器材輪轉與結束集合以現場指示為準。", status: "比賽通知" },
      { time: "晚間", title: "晚餐 · 韓式烤肉", subtitle: "練習後前往，旅行社安排", type: "food" },
      { time: "夜間", title: "入住 HOMES Stay Suwon", subtitle: "水原市八達區仁溪路 116", type: "hotel", mapQuery: "홈즈스테이 수원" },
    ],
  },
  {
    id: 2, date: "09/12", weekday: "六", title: "全日比賽", area: "水原",
    transport: "旅行社派車接送 · 不派導遊；HOMES Stay Suwon ↔ 水原農業生命科學高中",
    summary: ["全日比賽", "專車接送", "午晚餐自理"],
    places: [hotel, venue],
    events: [
      { time: "早上", title: "飯店早餐", subtitle: "飯店內享用", type: "food" },
      { time: "09:00 前", title: "抵達比賽場地", subtitle: "水原農業生命科學高中", type: "place", meta: "專車出發與上車時間仍需由旅行社公布。", mapQuery: "수원농생명과학고등학교 광교산로 13", status: "比賽通知" },
      { time: "09:00–09:50", title: "賽前練習", subtitle: "全體參賽者", type: "activity", status: "比賽通知" },
      { time: "11:00", title: "開幕式＆團體表演賽", subtitle: "第 1 個出場：童力／第 6 個出場：童力 36+", type: "activity", status: "比賽通知" },
      { time: "中午空檔", title: "午餐自理", subtitle: "首選：保榮餃子（仁溪店／鄰近分店）", type: "recommendation", recommendationId: "boyeong", meta: "以現場檢錄與 Level 2 開賽時間為優先；離場前先確認往返時間。" },
      { time: "14:30 起", title: "Level 2 比賽", subtitle: "實際檢錄與出場順序以現場公告為準", type: "activity", status: "比賽通知" },
      { time: "16:10 起", title: "Level 3 比賽", subtitle: "實際檢錄與出場順序以現場公告為準", type: "activity", status: "比賽通知" },
      { time: "晚餐", title: "晚餐自理", subtitle: "首選：佳甫亭水原排骨", type: "recommendation", recommendationId: "kabojung" },
      { time: "賽後", title: "專車返回飯店", subtitle: "HOMES Stay Suwon", type: "transport" },
    ],
  },
  {
    id: 3, date: "09/13", weekday: "日", title: "全日比賽", area: "水原",
    transport: "旅行社派車接送 · 不派導遊；HOMES Stay Suwon ↔ 水原農業生命科學高中",
    summary: ["全日比賽", "專車接送", "午晚餐自理"],
    places: [hotel, venue],
    events: [
      { time: "早上", title: "飯店早餐", subtitle: "飯店內享用", type: "food" },
      { time: "09:00 前", title: "抵達比賽場地", subtitle: "水原農業生命科學高中", type: "place", meta: "專車出發與上車時間仍需由旅行社公布。", mapQuery: "수원농생명과학고등학교 광교산로 13", status: "比賽通知" },
      { time: "09:00–09:50", title: "賽前練習", subtitle: "全體參賽者", type: "activity", status: "比賽通知" },
      { time: "10:00 起", title: "Level 4 比賽", subtitle: "實際檢錄與出場順序以現場公告為準", type: "activity", status: "比賽通知" },
      { time: "12:30 起", title: "Level 5–8 比賽", subtitle: "實際檢錄與出場順序以現場公告為準", type: "activity", status: "比賽通知" },
      { time: "14:00 起", title: "KGA（FIG）比賽", subtitle: "成人組列在此組", type: "activity", status: "比賽通知" },
      { time: "賽程空檔", title: "午餐自理", subtitle: "備選：柳池會館 · 水原醒酒湯", type: "recommendation", recommendationId: "yuchi", meta: "當日賽程密集，只有確認不影響檢錄與出場時才離場用餐；優先準備場館附近或可攜餐點。" },
      { time: "晚餐", title: "晚餐自理", subtitle: "首選：真味炸雞 · 水原炸雞街", type: "recommendation", recommendationId: "jinmi" },
      { time: "賽後", title: "專車返回飯店", subtitle: "HOMES Stay Suwon", type: "transport" },
    ],
  },
  {
    id: 4, date: "09/14", weekday: "一", title: "民俗博物館 · 韓屋村", area: "首爾",
    transport: "全日團體專車 · 水原往返首爾；市區站點間由遊覽車移動",
    summary: ["團體專車", "文化散策", "午晚餐已含"],
    places: [
      hotel,
      { name: "國立民俗博物館", query: "국립민속박물관", lat: 37.5815, lng: 126.9789 },
      { name: "通仁市場", query: "통인시장", lat: 37.5807, lng: 126.9699 },
      { name: "恩平韓屋村", query: "은평한옥마을", lat: 37.6418, lng: 126.9386 },
      { name: "北漢山景觀咖啡廳", query: "은평한옥마을 북한산 뷰 카페", lat: 37.6425, lng: 126.9394, note: "原行程未指定店名" },
    ],
    events: [
      { time: "早上", title: "飯店早餐後出發", subtitle: "水原 → 首爾 · 團體專車", type: "transport", meta: "車程約 1.5–2 小時，依交通狀況" },
      { time: "上午", title: "國立民俗博物館＋7080 懷舊街", subtitle: "從生活與風俗認識韓國歷史", type: "place", mapQuery: "국립민속박물관" },
      { time: "中午", title: "通仁市場", subtitle: "午餐為旅行社安排韓式風味餐", type: "food", meta: "可逛銅錢便當 Cafe 與傳統小菜攤", mapQuery: "통인시장" },
      { time: "午後", title: "恩平韓屋村", subtitle: "以北漢山為背景的現代韓屋聚落", type: "place", mapQuery: "은평한옥마을" },
      { time: "午後", title: "北漢山全景庭園咖啡廳", subtitle: "景觀咖啡休息", type: "place", meta: "店名尚待旅行社確認", mapQuery: "은평한옥마을 북한산 뷰 카페" },
      { time: "晚間", title: "韓式風味晚餐 · 返回飯店", subtitle: "旅行社安排 · 團體專車", type: "food" },
    ],
  },
  {
    id: 5, date: "09/15", weekday: "二", title: "水原 · 仁川 · 回家", area: "水原 → 仁川",
    transport: "全日團體專車＋月尾島遊船 · 最後送往仁川機場",
    summary: ["水原華城", "月尾島", "BR159"],
    places: [
      hotel,
      { name: "水原華城", query: "수원화성 화성행궁", lat: 37.2841, lng: 127.0142 },
      { name: "星空圖書館 2.0", query: "스타필드 수원 별마당도서관", lat: 37.2874, lng: 126.9912 },
      { name: "富平地下商街", query: "부평지하상가", lat: 37.4895, lng: 126.7245 },
      { name: "月尾島文化大街", query: "월미도 문화의거리", lat: 37.4747, lng: 126.5962 },
      { name: "仁川國際機場", query: "인천국제공항", lat: 37.4602, lng: 126.4407 },
    ],
    events: [
      { time: "早上", title: "飯店早餐 · 退房", subtitle: "行李上車後開始最後一天", type: "hotel" },
      { time: "上午", title: "世界文化遺產 · 水原華城", subtitle: "城牆、華虹門與訪花隨柳亭", type: "place", mapQuery: "수원화성 화성행궁" },
      { time: "中午", title: "午餐 · 馬鈴薯燉大骨", subtitle: "旅行社安排", type: "food" },
      { time: "午後", title: "星空圖書館 2.0", subtitle: "Starfield 水原 · 四層挑高書牆", type: "place", mapQuery: "스타필드 수원 별마당도서관" },
      { time: "午後", title: "仁川富平地下商街", subtitle: "地下街自由購物", type: "place", mapQuery: "부평지하상가" },
      { time: "傍晚", title: "月尾島國際街 · 海鷗船", subtitle: "海濱散步並搭船餵海鷗", type: "activity", mapQuery: "월미도 문화의거리" },
      { time: "19:45", title: "仁川機場起飛", subtitle: "長榮航空 BR159 · 晚餐為機上餐", type: "flight", meta: "21:25 抵達桃園", confirmed: true },
    ],
  },
];

export const recommendations = {
  boyeong: {
    name: "保榮餃子 · 보영만두", tag: "快速午餐", dish: "手工餃子＋辣拌麵",
    why: "上菜快、適合比賽空檔；飯店周邊可先用 Naver Map 確認當天最近分店。",
    query: "보영만두 인계점", source: "https://www.tripadvisor.com/RestaurantsNear-g424960-d13222654-HOMES_Stay_Suwon-Suwon_Gyeonggi_do.html",
  },
  kabojung: {
    name: "佳甫亭 · 가보정", tag: "水原名物", dish: "生牛排骨／調味牛排骨",
    why: "韓國觀光公社列為水原三大排骨名店之一，距飯店區域不遠；熱門時段建議訂位。",
    address: "경기도 수원시 팔달구 장다리로 282", query: "가보정", source: "https://english.visitkorea.or.kr/svc/whereToGo/locIntrdn/rgnContentsView.do?vcontsId=188614",
  },
  yuchi: {
    name: "柳池會館 · 유치회관", tag: "水原老味道", dish: "牛肉醒酒湯＋白切牛肉",
    why: "在地長年經營的醒酒湯專門店，湯飯飽足且適合比賽日快速補充體力。",
    address: "경기도 수원시 팔달구 효원로292번길 67", query: "유치회관 본점", source: "https://ggc.ggcf.kr/en/p/5a6a0325afeca47471384c19",
  },
  jinmi: {
    name: "真味炸雞 · 진미통닭", tag: "賽後聚餐", dish: "原味＋甜辣半半炸雞",
    why: "位於水原炸雞街；韓國觀光公社將真味、龍城列為街區代表店家。",
    address: "경기도 수원시 팔달구 정조로800번길 21", query: "진미통닭", source: "https://english.visitkorea.or.kr/svc/contents/contentsView.do?menuSn=351&vcontsId=176166",
  },
};

export const competitionVideos = [
  { apparatus: "地板", level: "LEVEL 6", videoId: "tInZgppayUw", start: 286, startLabel: "04:46", accent: "coral" },
  { apparatus: "單槓", level: "LEVEL 6", videoId: "yO_a5AxhztI", start: 114, startLabel: "01:54", accent: "green" },
  { apparatus: "跳馬", level: "LEVEL 7", videoId: "JdTx52W1Gn8", start: 72, startLabel: "01:12", accent: "sand" },
];

export const suwonFood = [
  {
    name: "佳甫亭", korean: "가보정", category: "水原王排骨", price: "高價位・適合聚餐",
    dishes: ["生牛排骨", "調味牛排骨", "大醬湯"],
    intro: "韓國觀光公社列出的水原三大排骨名店之一，規模大、配菜完整，是第一次吃水原王排骨的穩妥選擇。",
    tip: "熱門晚餐時段先訂位；想控制預算可查看平日午間套餐。",
    address: "경기도 수원시 팔달구 장다리로 282", query: "수원 가보정",
    lat: 37.2748, lng: 127.0316,
    source: "https://english.visitkorea.or.kr/svc/contents/contentsView.do?vcontsId=188614",
  },
  {
    name: "本水原排骨", korean: "본수원갈비", category: "50 年老店", price: "高價位・多人分享",
    dishes: ["水原王排骨", "調味排骨", "排骨湯"],
    intro: "超過 50 年歷史，同樣名列水原三大排骨店；可比較原味生排骨與甜鹹調味排骨。",
    tip: "排骨份量適合多人分享；平日午餐可留意限定排骨湯。",
    address: "경기도 수원시 팔달구 중부대로223번길 41", query: "본수원갈비",
    lat: 37.2804, lng: 127.0433,
    source: "https://english.visitkorea.or.kr/svc/whereToGo/locIntrdn/rgnContentsView.do?vcontsId=86767",
  },
  {
    name: "柳池會館", korean: "유치회관", category: "在地湯飯", price: "平價・快速用餐",
    dishes: ["牛肉醒酒湯", "白切牛肉", "蘿蔔泡菜"],
    intro: "水原代表性的清爽牛肉醒酒湯老店，湯裡有牛肉與白菜，血腸可依喜好另外加入。",
    tip: "適合比賽日補充體力；不吃牛血可在點餐時先說明。",
    address: "경기도 수원시 팔달구 효원로292번길 67", query: "유치회관 본점",
    lat: 37.2622, lng: 127.0346,
    source: "https://ggc.ggcf.kr/en/p/5a6a0325afeca47471384c19",
  },
  {
    name: "真味炸雞", korean: "진미통닭", category: "水原炸雞街", price: "中價位・適合分享",
    dishes: ["原味炸雞", "甜辣炸雞", "半半炸雞"],
    intro: "位於水原炸雞街的代表店家，以大鍋現炸、外脆內嫩的老式全雞聞名，適合賽後多人分享。",
    tip: "點半半可一次比較原味與甜辣；週末用餐尖峰可能需要候位。",
    address: "경기도 수원시 팔달구 정조로800번길 21", query: "수원 진미통닭",
    lat: 37.2794, lng: 127.0182,
    source: "https://english.visitkorea.or.kr/svc/contents/contentsView.do?menuSn=351&vcontsId=176166",
  },
  {
    name: "地洞市場血腸城", korean: "지동시장 순대타운", category: "傳統市場", price: "平價・在地小吃",
    dishes: ["綜合血腸", "炒血腸", "豬雜湯"],
    intro: "地洞市場美食巷聚集約 20 間血腸專門店，可一次體驗水原庶民市場料理與熱鬧氣氛。",
    tip: "內臟接受度因人而異；第一次可點小份綜合血腸多人分食。",
    address: "경기도 수원시 팔달구 팔달문로 19", query: "지동시장 순대타운",
    lat: 37.2777, lng: 127.0197,
    source: "https://www.suwon.go.kr/webcontent/ckeditor/2025/11/10/b36115dd-5223-49f8-80af-cf2906c6055a.pdf",
  },
  {
    name: "保榮餃子", korean: "보영만두 북문본점", category: "餃子與辣拌麵", price: "平價・快速用餐",
    dishes: ["蒸餃", "炸餃", "辣拌麵"],
    intro: "水原北門一帶廣為人知的餃子店，現做餃子配酸辣爽口的拌麵，是比賽空檔容易安排的一餐。",
    tip: "辣拌麵有辣度；可搭配蒸餃平衡味道，並先用 Naver Map 確認最近分店。",
    address: "경기도 수원시 장안구 팔달로 271", query: "보영만두 북문본점",
    lat: 37.2917, lng: 127.0122,
    source: "https://www.diningcode.com/profile.php?rid=qiiPwhoYeuEZ",
  },
];

export const shoppingCategories = [
  {
    id: "beauty", icon: "✦", name: "藥妝保養", note: "Olive Young／大創",
    source: "https://www.seoultourism.org/k-beauty-shopping-guide-seoul/",
    items: [
      { name: "Round Lab 白樺樹防曬", detail: "輕盈日常防曬；購買前依膚質試用。", priority: "人氣防曬" },
      { name: "Torriden Dive-In 精華", detail: "以補水為主的玻尿酸精華。", priority: "乾燥肌" },
      { name: "Mediheal／Biodance 面膜", detail: "單片好分送，留意 1+1 或多入組。", priority: "伴手禮" },
      { name: "VT Reedle Shot 100", detail: "有刺激感的入門版本，敏感肌先局部測試。", priority: "先試再買" },
    ],
  },
  {
    id: "makeup", icon: "●", name: "彩妝美妝", note: "先試色再結帳",
    source: "https://www.seoultourism.org/k-beauty-shopping-guide-seoul/",
    items: [
      { name: "Rom&nd／Peripera 唇彩", detail: "體積小、色號多，適合自用或送禮。", priority: "小禮物" },
      { name: "HERA／CLIO 氣墊粉餅", detail: "現場確認色階並一起購買補充蕊。", priority: "試色必須" },
      { name: "CLIO／Etude 眉筆", detail: "韓系自然眉色，確認髮色後挑選。", priority: "實用" },
      { name: "Laneige 唇膜", detail: "經典保濕小物，機場免稅也常有組合。", priority: "經典款" },
    ],
  },
  {
    id: "fashion", icon: "◇", name: "服飾配件", note: "Musinsa／聖水／弘大",
    source: "https://about.musinsa.com/newsroom/k-fashion-edit",
    items: [
      { name: "MUSINSA STANDARD 基本款", detail: "男女、童裝與運動線齊全，實穿且容易搭配。", priority: "基本款" },
      { name: "韓國設計師／街頭品牌", detail: "Musinsa Store 可一次看多個本地品牌。", priority: "K-Fashion" },
      { name: "帽子、襪子與帆布袋", detail: "體積小、價位相對親切，適合伴手禮。", priority: "好攜帶" },
      { name: "富平地下街服飾", detail: "Day 5 行程內可逛；先比價、確認尺寸與退換規則。", priority: "行程順買" },
    ],
  },
  {
    id: "snacks", icon: "□", name: "零食伴手禮", note: "超市／便利商店",
    source: "https://www.seoultourism.org/what-to-buy-in-korea/",
    items: [
      { name: "HBAF 杏仁", detail: "蜂蜜奶油等多口味，小包裝容易分送。", priority: "熱門" },
      { name: "韓國海苔／海苔脆片", detail: "輕巧好帶，注意包裝避免行李擠壓。", priority: "家庭禮" },
      { name: "限定口味泡麵與零食", detail: "超市通常比觀光區選擇多；留意肉類成分入境限制。", priority: "限定款" },
      { name: "柚子茶／傳統茶包", detail: "玻璃罐較重，優先挑補充包或茶包。", priority: "長輩禮" },
    ],
  },
  {
    id: "goods", icon: "+", name: "生活與紀念品", note: "大創／仁寺洞／官方店",
    source: "https://english.visitkorea.or.kr/svc/contents/contentsView.do?dataSetId=120&menuSn=929&vcontsId=251858",
    items: [
      { name: "Daiso 收納與旅行小物", detail: "收納袋、旅行分裝瓶、文具實用且平價。", priority: "高 CP" },
      { name: "韓紙文具／傳統紋樣小物", detail: "書籤、卡片、杯墊適合有韓國特色的禮物。", priority: "文化紀念" },
      { name: "正版 K-pop 專輯與周邊", detail: "優先官方商店或大型唱片行，避免非官方商品。", priority: "認明正版" },
      { name: "水原限定點心", detail: "可留意水原藥果、華城造型餅乾等地方紀念品。", priority: "水原限定" },
    ],
  },
];

export { googleSearch, naverSearch };
